# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['TSSPrint.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'servicemanager', 
        'win32timezone', 
        'win32print', 
        'win32service', 
        'win32serviceutil', 
        'pywintypes', 
        'win32event',
        'win32api',
        'win32con',
        'win32security',
        'win32evtlog',
        'win32evtlogutil',
        'win32file',
        'win32pipe',
        'win32process',
        'winerror',
        'threading',
        'json',
        'time',
        're',
        'traceback',
        'platform',
        'socket',
        'sys',
        'websocket_server'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='TSSPrint',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
